language: node_js
os:
  - linux
node_js:
  - "10"

script:
  - npm test
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload

before_install:
  - if [[ `npm -v` != 6* ]]; then npm install -g npm@6; fi
  - npm install -g greenkeeper-lockfile@2
# there is an issue with lerna and npm ci so we
# working around this with a piece of code taken
# from https://github.com/greenkeeperio/greenkeeper-lockfile/issues/156
install: case $TRAVIS_BRANCH in greenkeeper*) npm i;; *) npm ci;; esac;

