language: node_js
os:
  - linux
node_js:
  - "10"

script:
  - npm test
before_script:
  - greenkeeper-lockfile-update
after_script:
  - greenkeeper-lockfile-upload

before_install:
  - npm install -g greenkeeper-lockfile@2
install:
  - npm install

