language: node_js

os:
  - linux
  - osx


node_js:
  - "v10.16.3"
  - "v12.8.1"

compiler:
  - gcc
  - clang

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6

script:
  - npm run build
  - npm test
  - npm run lint


